In [7]:
import requests
import pandas as pd

In [8]:
resp_dev = requests.get("https://github.com/tciodaro/eng_ml/raw/refs/heads/main/data/dataset_kobe_dev.parquet")
with open("file_dev.parquet", "wb") as file_dev:
    file_dev.write(resp_dev.content)

resp_prod = requests.get("https://github.com/tciodaro/eng_ml/raw/refs/heads/main/data/dataset_kobe_prod.parquet")
with open("file_prod.parquet", "wb") as file_prod:
    file_prod.write(resp_prod.content)

In [9]:
df_dev = pd.read_parquet("file_dev.parquet")
df_prod = pd.read_parquet("file_prod.parquet")

In [10]:

def descricao_dados(base):
    # criar um dataframe de nomes das colunas
    base_var_df = pd.DataFrame(base.columns.tolist(), columns=["Nome das variáveis"])
    
    # inserir no dataframe os tipos das colunas
    base_var_df["Tipo"] = base.dtypes.tolist()
    
    # inserir no dataframe a quantidade de missing values
    base_var_df["Nr. de missing values"] = base.isnull().sum().tolist()
    
    # inserir no dataframe a quantidade de observacoes
    base_var_df["Nr. de observações"] = base.count().tolist()

    return base_var_df

In [19]:
teste = descricao_dados(df_dev)
teste

    Nome das variáveis     Tipo  Nr. de missing values  Nr. de observações
0          action_type   object                      0               24271
1   combined_shot_type   object                      0               24271
2        game_event_id    int64                      0               24271
3              game_id    int64                      0               24271
4                  lat  float64                      0               24271
5                loc_x    int64                      0               24271
6                loc_y    int64                      0               24271
7                  lon  float64                      0               24271
8    minutes_remaining    int64                      0               24271
9               period    int64                      0               24271
10            playoffs    int64                      0               24271
11              season   object                      0               24271
12   seconds_remaining    int64                      0               24271
13       shot_distance    int64                      0               24271
14      shot_made_flag  float64                   3986               20285
15           shot_type   object                      0               24271
16      shot_zone_area   object                      0               24271
17     shot_zone_basic   object                      0               24271
18     shot_zone_range   object                      0               24271
19             team_id    int64                      0               24271
20           team_name   object                      0               24271
21           game_date   object                      0               24271
22             matchup   object                      0               24271
23            opponent   object                      0               24271
24             shot_id    int64                      0               24271

In [20]:
dataset_kobe_dev_formated = df_dev.dropna(subset=['shot_made_flag'])
teste = descricao_dados(dataset_kobe_dev_formated)
teste

    Nome das variáveis     Tipo  Nr. de missing values  Nr. de observações
0          action_type   object                      0               20285
1   combined_shot_type   object                      0               20285
2        game_event_id    int64                      0               20285
3              game_id    int64                      0               20285
4                  lat  float64                      0               20285
5                loc_x    int64                      0               20285
6                loc_y    int64                      0               20285
7                  lon  float64                      0               20285
8    minutes_remaining    int64                      0               20285
9               period    int64                      0               20285
10            playoffs    int64                      0               20285
11              season   object                      0               20285
12   seconds_remaining    int64                      0               20285
13       shot_distance    int64                      0               20285
14      shot_made_flag  float64                      0               20285
15           shot_type   object                      0               20285
16      shot_zone_area   object                      0               20285
17     shot_zone_basic   object                      0               20285
18     shot_zone_range   object                      0               20285
19             team_id    int64                      0               20285
20           team_name   object                      0               20285
21           game_date   object                      0               20285
22             matchup   object                      0               20285
23            opponent   object                      0               20285
24             shot_id    int64                      0               20285